/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimelapseTimelapseIdRouteImport } from './routes/timelapse.$timelapseId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'
import { Route as ChallengesChallengeIdRouteImport } from './routes/challenges.$challengeId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelapseTimelapseIdRoute = TimelapseTimelapseIdRouteImport.update({
  id: '/timelapse/$timelapseId',
  path: '/timelapse/$timelapseId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/$clubId',
  path: '/$clubId',
  getParentRoute: () => ClubsRoute,
} as any)
const ChallengesChallengeIdRoute = ChallengesChallengeIdRouteImport.update({
  id: '/$challengeId',
  path: '/$challengeId',
  getParentRoute: () => ChallengesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/clubs': typeof ClubsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/timelapse/$timelapseId': typeof TimelapseTimelapseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/clubs': typeof ClubsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/timelapse/$timelapseId': typeof TimelapseTimelapseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/clubs': typeof ClubsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/timelapse/$timelapseId': typeof TimelapseTimelapseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/challenges'
    | '/clubs'
    | '/leaderboard'
    | '/projects'
    | '/challenges/$challengeId'
    | '/clubs/$clubId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/timelapse/$timelapseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/challenges'
    | '/clubs'
    | '/leaderboard'
    | '/projects'
    | '/challenges/$challengeId'
    | '/clubs/$clubId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/timelapse/$timelapseId'
  id:
    | '__root__'
    | '/'
    | '/anotherPage'
    | '/challenges'
    | '/clubs'
    | '/leaderboard'
    | '/projects'
    | '/challenges/$challengeId'
    | '/clubs/$clubId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/timelapse/$timelapseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherPageRoute: typeof AnotherPageRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  ClubsRoute: typeof ClubsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TimelapseTimelapseIdRoute: typeof TimelapseTimelapseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timelapse/$timelapseId': {
      id: '/timelapse/$timelapseId'
      path: '/timelapse/$timelapseId'
      fullPath: '/timelapse/$timelapseId'
      preLoaderRoute: typeof TimelapseTimelapseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/challenges/$challengeId': {
      id: '/challenges/$challengeId'
      path: '/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof ChallengesChallengeIdRouteImport
      parentRoute: typeof ChallengesRoute
    }
  }
}

interface ChallengesRouteChildren {
  ChallengesChallengeIdRoute: typeof ChallengesChallengeIdRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesChallengeIdRoute: ChallengesChallengeIdRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

interface ClubsRouteChildren {
  ClubsClubIdRoute: typeof ClubsClubIdRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsClubIdRoute: ClubsClubIdRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherPageRoute: AnotherPageRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  ClubsRoute: ClubsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TimelapseTimelapseIdRoute: TimelapseTimelapseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
