/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated.subscription'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated.leaderboard'
import { Route as AuthenticatedClubsRouteImport } from './routes/_authenticated.clubs'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated.challenges'
import { Route as AuthenticatedAutumnDemoRouteImport } from './routes/_authenticated.autumn-demo'
import { Route as AuthenticatedAnotherPageRouteImport } from './routes/_authenticated.anotherPage'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedTimelapseTimelapseIdRouteImport } from './routes/_authenticated.timelapse.$timelapseId'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated.sessions.$sessionId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedClubsClubIdRouteImport } from './routes/_authenticated.clubs.$clubId'
import { Route as AuthenticatedChallengesChallengeIdRouteImport } from './routes/_authenticated.challenges.$challengeId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClubsRoute = AuthenticatedClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutumnDemoRoute = AuthenticatedAutumnDemoRouteImport.update({
  id: '/autumn-demo',
  path: '/autumn-demo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnotherPageRoute =
  AuthenticatedAnotherPageRouteImport.update({
    id: '/anotherPage',
    path: '/anotherPage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelapseTimelapseIdRoute =
  AuthenticatedTimelapseTimelapseIdRouteImport.update({
    id: '/timelapse/$timelapseId',
    path: '/timelapse/$timelapseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedClubsClubIdRoute =
  AuthenticatedClubsClubIdRouteImport.update({
    id: '/$clubId',
    path: '/$clubId',
    getParentRoute: () => AuthenticatedClubsRoute,
  } as any)
const AuthenticatedChallengesChallengeIdRoute =
  AuthenticatedChallengesChallengeIdRouteImport.update({
    id: '/$challengeId',
    path: '/$challengeId',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/anotherPage': typeof AuthenticatedAnotherPageRoute
  '/autumn-demo': typeof AuthenticatedAutumnDemoRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/clubs': typeof AuthenticatedClubsRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/': typeof AuthenticatedIndexRoute
  '/challenges/$challengeId': typeof AuthenticatedChallengesChallengeIdRoute
  '/clubs/$clubId': typeof AuthenticatedClubsClubIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/timelapse/$timelapseId': typeof AuthenticatedTimelapseTimelapseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/anotherPage': typeof AuthenticatedAnotherPageRoute
  '/autumn-demo': typeof AuthenticatedAutumnDemoRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/clubs': typeof AuthenticatedClubsRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/': typeof AuthenticatedIndexRoute
  '/challenges/$challengeId': typeof AuthenticatedChallengesChallengeIdRoute
  '/clubs/$clubId': typeof AuthenticatedClubsClubIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/timelapse/$timelapseId': typeof AuthenticatedTimelapseTimelapseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/anotherPage': typeof AuthenticatedAnotherPageRoute
  '/_authenticated/autumn-demo': typeof AuthenticatedAutumnDemoRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/_authenticated/clubs': typeof AuthenticatedClubsRouteWithChildren
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/challenges/$challengeId': typeof AuthenticatedChallengesChallengeIdRoute
  '/_authenticated/clubs/$clubId': typeof AuthenticatedClubsClubIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/timelapse/$timelapseId': typeof AuthenticatedTimelapseTimelapseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/anotherPage'
    | '/autumn-demo'
    | '/challenges'
    | '/clubs'
    | '/leaderboard'
    | '/projects'
    | '/subscription'
    | '/'
    | '/challenges/$challengeId'
    | '/clubs/$clubId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/timelapse/$timelapseId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anotherPage'
    | '/autumn-demo'
    | '/challenges'
    | '/clubs'
    | '/leaderboard'
    | '/projects'
    | '/subscription'
    | '/'
    | '/challenges/$challengeId'
    | '/clubs/$clubId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/timelapse/$timelapseId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/anotherPage'
    | '/_authenticated/autumn-demo'
    | '/_authenticated/challenges'
    | '/_authenticated/clubs'
    | '/_authenticated/leaderboard'
    | '/_authenticated/projects'
    | '/_authenticated/subscription'
    | '/_authenticated/'
    | '/_authenticated/challenges/$challengeId'
    | '/_authenticated/clubs/$clubId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/timelapse/$timelapseId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clubs': {
      id: '/_authenticated/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AuthenticatedClubsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/autumn-demo': {
      id: '/_authenticated/autumn-demo'
      path: '/autumn-demo'
      fullPath: '/autumn-demo'
      preLoaderRoute: typeof AuthenticatedAutumnDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anotherPage': {
      id: '/_authenticated/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AuthenticatedAnotherPageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timelapse/$timelapseId': {
      id: '/_authenticated/timelapse/$timelapseId'
      path: '/timelapse/$timelapseId'
      fullPath: '/timelapse/$timelapseId'
      preLoaderRoute: typeof AuthenticatedTimelapseTimelapseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/clubs/$clubId': {
      id: '/_authenticated/clubs/$clubId'
      path: '/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof AuthenticatedClubsClubIdRouteImport
      parentRoute: typeof AuthenticatedClubsRoute
    }
    '/_authenticated/challenges/$challengeId': {
      id: '/_authenticated/challenges/$challengeId'
      path: '/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof AuthenticatedChallengesChallengeIdRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
  }
}

interface AuthenticatedChallengesRouteChildren {
  AuthenticatedChallengesChallengeIdRoute: typeof AuthenticatedChallengesChallengeIdRoute
}

const AuthenticatedChallengesRouteChildren: AuthenticatedChallengesRouteChildren =
  {
    AuthenticatedChallengesChallengeIdRoute:
      AuthenticatedChallengesChallengeIdRoute,
  }

const AuthenticatedChallengesRouteWithChildren =
  AuthenticatedChallengesRoute._addFileChildren(
    AuthenticatedChallengesRouteChildren,
  )

interface AuthenticatedClubsRouteChildren {
  AuthenticatedClubsClubIdRoute: typeof AuthenticatedClubsClubIdRoute
}

const AuthenticatedClubsRouteChildren: AuthenticatedClubsRouteChildren = {
  AuthenticatedClubsClubIdRoute: AuthenticatedClubsClubIdRoute,
}

const AuthenticatedClubsRouteWithChildren =
  AuthenticatedClubsRoute._addFileChildren(AuthenticatedClubsRouteChildren)

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnotherPageRoute: typeof AuthenticatedAnotherPageRoute
  AuthenticatedAutumnDemoRoute: typeof AuthenticatedAutumnDemoRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRouteWithChildren
  AuthenticatedClubsRoute: typeof AuthenticatedClubsRouteWithChildren
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedTimelapseTimelapseIdRoute: typeof AuthenticatedTimelapseTimelapseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnotherPageRoute: AuthenticatedAnotherPageRoute,
  AuthenticatedAutumnDemoRoute: AuthenticatedAutumnDemoRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRouteWithChildren,
  AuthenticatedClubsRoute: AuthenticatedClubsRouteWithChildren,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedTimelapseTimelapseIdRoute:
    AuthenticatedTimelapseTimelapseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
